services:
  # Go application service
  apptrak:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
    container_name: apptrak
    ports:
      - "5000:5000"  # Expose port 5000 (or your desired port)
    environment:
      - DSN=${DSN}  # Updated DSN for MySQL service
    depends_on:
      db:
        condition: service_healthy
    networks:
      - apptrak-network
    restart: unless-stopped

  # MySQL service
  db:
    image: mysql:8.0
    container_name: apptrak-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Named volume for MySQL data
      - ./pkg/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - apptrak-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  apptrak-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
